permalink: /blog/:year/:month/:day/:title
markdown: redcarpet

# Uncomment below for local testing. It will build much faster since it doesn't have to look through all those directories.
# exclude: [apps, built-apps, node_modules, packages, ui]